spring:
    application:
        name: email-service
    mail:
      host: smtp.gmail.com
      port: 587
      username: alok.ku.singh@gmail.com
      #password: provided at runtime
      test-connection: false
      properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true
          debug: true

email:
  username: alok.ku.singh
  #password: provided at runtime
  host: imap.gmail.com
  port: 993
  mailbox: INBOX
  pollRate: 30000

server:
  port: 8085
